
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name : http
      port: 15672
      nodePort : 30072
    - name : endpoint
      port : 5672
  selector:
    app: dwg-queue
  type : NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
subsets:
  - addresses:
      - ip: 172.20.0.1
    ports:
      - port: 3306


    