apiVersion : v1
kind : PersistentVolumeClaim
metadata :
    name : dwg-pvc
spec : 
    storageClassName : dwg-storage
    accessModes :
        - ReadWriteOnce
    resources : 
        requests : 
            storage : 20Gi

---
# how do we want it implemented

apiVersion : v1
kind : PersistentVolume
metadata :
    name : storage-local-dwg
spec : 
    storageClassName : dwg-storage
    capacity :
        storage : 20Gi
    accessModes :
        - ReadWriteOnce
    hostPath :
        path : "/hosthome/yossefaz/Documents/ness/dwg_transformer/uploads"
        type : DirectoryOrCreate