#apiVersion : apps/v1
#kind : Deployment
#metadata :
#    name : dwg-nginx
#spec :
#    selector :
#        matchLabels :
#            app : dwg-nginx
#    replicas : 1
#    template :
#        metadata :
#            labels :
#                app : dwg-nginx
#        spec :
#            containers :
#                - name : dwg-nginx
#                  image : yossefazoulay/dwg-nginx
#
---

apiVersion : apps/v1
kind : Deployment
metadata :
    name : dwg-controller
spec :
    selector :
        matchLabels :
            app : dwg-controller
    replicas : 1
    template :
        metadata :
            labels :
                app : dwg-controller
        spec :
            containers :
                - name : dwg-controller
                  image : yossefazoulay/dwg-controller
                  env :
                    - name: POOL_INTERVAL
                      value: "30"
                    - name: DEV_PROD
                      value: "prod"
                    - name: CAD_STATUS
                      value: "CAD_check_status"
                    - name: CAD_ERRORS
                      value: "CAD_check_errors"
                    - name : DB
                      value : "mysql"
                    - name : SCHEMA
                      value: "dwg_transformer"
                  volumeMounts:
                    - name: dwg-persistent-storage
                      mountPath: /app/shared
            volumes:
              - name: dwg-persistent-storage
                persistentVolumeClaim:
                  claimName: dwg-pvc

---
apiVersion : apps/v1
kind : Deployment
metadata :
    name : dwg-transformer
spec :
    selector :
        matchLabels :
            app : dwg-transformer
    replicas : 1
    template :
        metadata :
            labels :
                app : dwg-transformer
        spec :
            containers :
                - name : dwg-transformer
                  image : yossefazoulay/dwg-transformer
                  env :
                    - name: DEV_PROD
                      value: "prod"
                    - name: EXPORT_FORMAT
                      value: "DXF"
                  volumeMounts:
                    - name: dwg-persistent-storage
                      mountPath: /app/shared
            volumes :
                - name : dwg-persistent-storage
                  persistentVolumeClaim :
                    claimName : dwg-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dwg-queue
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwg-queue
  template:
    metadata:
      labels:
        app: dwg-queue
    spec:
      containers:
      - image: rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
---
apiVersion : apps/v1
kind : Deployment
metadata :
  name : dwg-worker
spec :
  selector :
    matchLabels :
      app : dwg-worker
  replicas : 1
  template :
    metadata :
      labels :
        app : dwg-worker
    spec :
      containers :
        - name : dwg-worker
          image : yossefazoulay/dwg-worker
          env:
            - name: DEV_PROD
              value: "prod"
          volumeMounts:
            - name: dwg-persistent-storage
              mountPath: /app/shared
      volumes :
        - name : dwg-persistent-storage
          persistentVolumeClaim :
            claimName : dwg-pvc
---
apiVersion : apps/v1
kind : Deployment
metadata :
  name : dwg-dal
spec :
  selector :
    matchLabels :
      app : dwg-dal
  replicas : 1
  template :
    metadata :
      labels :
        app : dwg-dal
    spec :
      containers :
        - name : dwg-dal
          image : yossefazoulay/dwg-dal
          env:
            - name: DEV_PROD
              value: "prod"
          volumeMounts:
            - name: dwg-persistent-storage
              mountPath: /app/shared
      volumes:
        - name: dwg-persistent-storage
          persistentVolumeClaim:
            claimName: dwg-pvc
---
    
