apiVersion : v1
kind : Service
metadata : 
    name : controller
spec :
    selector :
        app : dwg-controller
    type : ClusterIP
---
apiVersion : v1
kind : Service
metadata :
    name : transformer
spec :
    selector :
        app : dwg-transformer
    type : ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: dwg-queue
    component: rabbitmq

---
apiVersion : v1
kind : Service
metadata :
  name : worker
spec :
  selector :
    app : dwg-worker
  type : ClusterIP
---
    