apiVersion : v1
kind : Service
metadata : 
    name : server 
spec :
    selector :
        app : dwg-nginx
    ports :
        - name : server-http
          port : 80
          nodePort : 30080
    type : NodePort
---
apiVersion : v1
kind : Service
metadata : 
    name : controller
spec :
    selector :
        app : dwg-controller
    ports :
        - name : controller-http
          port : 3030
    type : ClusterIP
---
apiVersion : v1
kind : Service
metadata :
    name : transformer
spec :
    selector :
        app : dwg-transformer
    ports :
        - name : transformer-http
          port : 8090
    type : ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-internal
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
  selector:
    app: rabbitmq  
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  selector:
    app: rabbitmq
  ports:
   - name: rabbitmq-mgmt-port
     protocol: TCP
     port: 15672
     targetPort: 15672
   - name: rabbitmq-amqp-port
     protocol: TCP
     port: 5672
     targetPort: 5672
    