apiVersion : v1
kind : Service
metadata : 
    name : server 
spec :
    selector :
        app : dwg-nginx
    ports :
        - name : server-http
          port : 80
          nodePort : 30080
    type : NodePort
---
apiVersion : v1
kind : Service
metadata : 
    name : controller
spec :
    selector :
        app : dwg-controller
    ports :
        - name : controller-http
          port : 3030
    type : ClusterIP
---
apiVersion : v1
kind : Service
metadata :
    name : transformer
spec :
    selector :
        app : dwg-transformer
    ports :
        - name : transformer-http
          port : 8090
    type : ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
    